# =============================================================================
# tom_dashboard_v1.0.py
# Last updated: 2026-02-21
# =============================================================================
# v1.0: Initial dashboard - reads TOM CSVs, builds 4-panel GitHub Pages output
#
# PANELS:
#   1. Consistent TOM Longs  (filtered: no vol products, 5Y+ history, BH>0)
#   2. Vol/Hedge Timing       (vol ETPs shown separately)
#   3. Newly Working Watch    (1Y edge > 10%, lower conviction)
#   4. Short / Avoid TOM      (positive BH but negative TOM in last 1Y)
#
# DATA SOURCE: CSVs generated by tom_full_scan_v3.py (same directory)
# RUN: python tom_dashboard_v1.0.py  (from market-dashboards\)
# =============================================================================

import os
import sys
import pandas as pd
import numpy as np
import json

# ---------------------------------------------------------------------------
# Paths — CSVs live alongside this script in market-dashboards\
# ---------------------------------------------------------------------------
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# dashboard_writer lives in same directory
if _SCRIPT_DIR not in sys.path:
    sys.path.insert(0, _SCRIPT_DIR)

try:
    from dashboard_writer import DashboardWriter, write_landing_page
except ImportError:
    print('ERROR: dashboard_writer.py not found in', _SCRIPT_DIR)
    sys.exit(1)

# ---------------------------------------------------------------------------
# CSV filenames (all in _SCRIPT_DIR)
# ---------------------------------------------------------------------------
F_CONSISTENT  = os.path.join(_SCRIPT_DIR, 'tom_CONSISTENT_performers.csv')
F_NEWLY       = os.path.join(_SCRIPT_DIR, 'tom_NEWLY_working.csv')
F_SHORT_1Y    = os.path.join(_SCRIPT_DIR, 'tom_SHORT_candidates_1Y.csv')
F_SUMMARY     = os.path.join(_SCRIPT_DIR, 'tom_SUMMARY.csv')

# ---------------------------------------------------------------------------
# Vol / inverse products to pull into their own panel
# ---------------------------------------------------------------------------
VOL_TICKERS = {'UVXY', 'VXX', 'VIXY', 'VIXM', 'VXZ', 'TAIL',
               'DOG', 'HDGE', 'UNG', 'INBS', 'NBY'}

# ---------------------------------------------------------------------------
# Filtering thresholds
# ---------------------------------------------------------------------------
MIN_YEARS_CONSISTENT = 5.0   # Minimum full-history years for panel 1
MIN_BH_CONSISTENT    = 0.0   # Minimum B&H CAGR for panel 1
MIN_1Y_NEWLY         = 10.0  # Minimum 1Y outperform for panel 3
MIN_BH_SHORT         = 0.0   # Panel 4: only show assets with positive B&H


# =============================================================================
# DATA LOADING
# =============================================================================

def load_csvs():
    """Load all required CSVs. Returns dict of DataFrames."""
    dfs = {}
    for key, path in [
        ('consistent', F_CONSISTENT),
        ('newly',      F_NEWLY),
        ('short_1y',   F_SHORT_1Y),
        ('summary',    F_SUMMARY),
    ]:
        if not os.path.exists(path):
            print(f'WARNING: {path} not found — panel will be empty')
            dfs[key] = pd.DataFrame()
        else:
            dfs[key] = pd.read_csv(path, encoding='utf-8')
    return dfs


def parse_summary(df):
    """Extract scalar values from summary CSV."""
    if df.empty:
        return {}
    row = df.iloc[0]
    return {
        'total':      int(row.get('Total_Assets', 0)),
        'consistent': int(row.get('Consistent_Performers', 0)),
        'newly':      int(row.get('Newly_Working', 0)),
        'stopped':    int(row.get('Stopped_Working', 0)),
        'run_date':   str(row.get('Run_Date', 'N/A')),
    }


def filter_consistent(df):
    """Split consistent performers into tradeable longs and vol panel."""
    if df.empty:
        return pd.DataFrame(), pd.DataFrame()

    vol_mask = df['Ticker'].isin(VOL_TICKERS)

    # Vol panel — all vol products regardless of other filters
    vol_df = df[vol_mask].copy()

    # Tradeable longs — exclude vol, apply quality filters
    longs_df = df[
        (~vol_mask) &
        (df.get('Full_Years', pd.Series(dtype=float)) >= MIN_YEARS_CONSISTENT) &
        (df.get('Full_BH_CAGR', pd.Series(dtype=float)) > MIN_BH_CONSISTENT)
    ].copy()

    return longs_df, vol_df


def filter_newly(df):
    if df.empty:
        return df
    col = '1Y_LongTOM_Outperform'
    if col in df.columns:
        return df[df[col] >= MIN_1Y_NEWLY].copy()
    return df


def filter_short(df):
    if df.empty:
        return df
    col = '1Y_BH_CAGR'
    if col in df.columns:
        return df[df[col] > MIN_BH_SHORT].copy()
    return df


# =============================================================================
# JS / CSS
# =============================================================================

EXTRA_CSS = """
.tom-note {
    font-size: 0.85em;
    color: #555;
    padding: 8px 0 14px 0;
}
.tom-warn-banner {
    background: #fef3c7;
    border-left: 4px solid #d97706;
    padding: 10px 14px;
    font-size: 0.88em;
    color: #92400e;
    margin-bottom: 14px;
    border-radius: 0 6px 6px 0;
}
.tom-vol-banner {
    background: #ede9fe;
    border-left: 4px solid #7c3aed;
    padding: 10px 14px;
    font-size: 0.88em;
    color: #4c1d95;
    margin-bottom: 14px;
    border-radius: 0 6px 6px 0;
}
.tom-short-banner {
    background: #fee2e2;
    border-left: 4px solid #dc2626;
    padding: 10px 14px;
    font-size: 0.88em;
    color: #7f1d1d;
    margin-bottom: 14px;
    border-radius: 0 6px 6px 0;
}
.tom-table-wrap {
    overflow-x: auto;
    margin: 0;
}
.tom-table {
    width: 100%;
    border-collapse: collapse;
    font-size: 0.92em;
}
.tom-table colgroup col.col-ticker { width: 90px; }
.tom-table colgroup col.col-num    { width: 130px; }
.tom-table colgroup col.col-wr     { width: 100px; }
.tom-table thead tr.grp-row th {
    padding: 6px 10px;
    font-size: 0.80em;
    font-weight: 700;
    letter-spacing: 0.05em;
    text-align: center;
    border-bottom: none;
}
.tom-table thead tr.col-row th {
    padding: 6px 10px;
    font-size: 0.78em;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.04em;
    color: #374151;
    background: #f8f9fb;
    border-bottom: 2px solid #e5e7eb;
    cursor: pointer;
    white-space: nowrap;
    text-align: right;
}
.tom-table thead tr.col-row th.col-ticker-h {
    text-align: left;
}
.tom-table tbody tr:hover { background: #f0f4ff; }
.tom-table tbody td {
    padding: 7px 10px;
    border-bottom: 1px solid #f0f0f0;
    font-family: 'IBM Plex Mono', monospace;
    font-size: 0.90em;
    text-align: right;
    white-space: nowrap;
}
.tom-table tbody td.col-ticker {
    text-align: left;
    font-weight: 700;
    color: #1e293b;
    font-family: 'IBM Plex Mono', monospace;
}
.tom-table tbody td.cell-miss { color: #bbb; text-align: center; }
.tom-table .sorted-asc::after  { content: ' \u25b2'; color: #4f46e5; }
.tom-table .sorted-desc::after { content: ' \u25bc'; color: #4f46e5; }
"""

# Gradient + sort JS embedded once, used by all 4 tables
RENDER_JS = r"""
(function() {
    // --- Gradient: red(0) -> orange -> yellow -> green(1) ---
    function getGradientColor(n01) {
        const c = Math.max(0, Math.min(1, n01));
        let r, g, b;
        if (c < 0.25) {
            const t = c * 4;
            r = Math.round(211 + (255-211)*t); g = Math.round(47 + (152-47)*t); b = 0;
        } else if (c < 0.5) {
            const t = (c-0.25)*4;
            r = 255; g = Math.round(152 + (235-152)*t); b = Math.round(59*t);
        } else if (c < 0.75) {
            const t = (c-0.5)*4;
            r = Math.round(255 + (139-255)*t); g = Math.round(235 + (195-235)*t); b = Math.round(59 + (74-59)*t);
        } else {
            const t = (c-0.75)*4;
            r = Math.round(139*(1-t)); g = Math.round(195 + (200-195)*t); b = Math.round(74 + (83-74)*t);
        }
        return `rgb(${r},${g},${b})`;
    }

    function textColor(bgRgb) {
        const m = bgRgb.match(/rgb\((\d+),(\d+),(\d+)\)/);
        if (!m) return '#000';
        return (0.299*m[1] + 0.587*m[2] + 0.114*m[3]) > 140 ? '#000' : '#fff';
    }

    // Per-table sort state
    const sortState = {};

    // Percentile range helper (5th-95th)
    function calcRange(vals) {
        const clean = vals.filter(v => v != null && !isNaN(v));
        if (!clean.length) return null;
        const s = [...clean].sort((a, b) => a - b);
        return {
            min: s[Math.floor(s.length * 0.05)],
            max: s[Math.floor(s.length * 0.95)]
        };
    }

    function normalize(val, range) {
        if (val == null || isNaN(val) || !range || range.max === range.min) return 0.5;
        return Math.max(0, Math.min(1, (val - range.min) / (range.max - range.min)));
    }

    function colorCell(val, range, fmt) {
        if (val == null || isNaN(val)) return '<td class="cell-miss">—</td>';
        const bg = getGradientColor(normalize(val, range));
        const fg = textColor(bg);
        return `<td style="background:${bg};color:${fg};text-align:right;">${fmt(val)}</td>`;
    }

    function pct(v, decimals=2) {
        if (v == null || isNaN(v)) return '—';
        return (v >= 0 ? '+' : '') + v.toFixed(decimals) + '%';
    }

    function plainPct(v, decimals=1) {
        if (v == null || isNaN(v)) return '—';
        return v.toFixed(decimals) + '%';
    }

    // -------------------------------------------------------------------------
    // Generic table renderer
    // -------------------------------------------------------------------------
    // schema: array of {key, label, fmt, color: bool, invert: bool (lower=better)}
    // rows: array of objects
    function renderTable(tableId, rows, schema, sortKey) {
        const el = document.getElementById(tableId);
        if (!el) return;

        const ss = sortState[tableId] || { col: sortKey || schema[1].key, dir: 'desc' };
        sortState[tableId] = ss;

        // Compute ranges per column
        const ranges = {};
        schema.forEach(col => {
            if (col.color) {
                ranges[col.key] = calcRange(rows.map(r => r[col.key]));
            }
        });

        // Sort
        const sorted = [...rows].sort((a, b) => {
            const va = a[ss.col] != null ? a[ss.col] : -9999;
            const vb = b[ss.col] != null ? b[ss.col] : -9999;
            if (typeof va === 'string') return ss.dir === 'asc' ? va.localeCompare(vb) : vb.localeCompare(va);
            return ss.dir === 'asc' ? va - vb : vb - va;
        });

        const thClick = (col) => {
            if (sortState[tableId].col === col) {
                sortState[tableId].dir = sortState[tableId].dir === 'asc' ? 'desc' : 'asc';
            } else {
                sortState[tableId] = { col, dir: 'desc' };
            }
            renderTable(tableId, rows, schema, sortKey);
        };

        // Build header
        const curSort = sortState[tableId];
        let html = '<table class="tom-table"><colgroup>';
        schema.forEach(col => {
            html += `<col class="${col.key === 'Ticker' ? 'col-ticker' : col.key === '1Y_TOM_WinRate' || col.key === '1Y_ShortTOM_WinRate' ? 'col-wr' : 'col-num'}">`;
        });
        html += '</colgroup><thead><tr class="col-row">';
        schema.forEach(col => {
            const sortClass = curSort.col === col.key ? (curSort.dir === 'asc' ? 'sorted-asc' : 'sorted-desc') : '';
            const isLeft = col.key === 'Ticker';
            html += `<th class="${isLeft ? 'col-ticker-h' : ''} ${sortClass}" onclick="(${thClick.toString()})('${col.key}')">${col.label}</th>`;
        });
        html += '</tr></thead><tbody>';

        sorted.forEach(row => {
            html += '<tr>';
            schema.forEach(col => {
                if (col.key === 'Ticker') {
                    html += `<td class="col-ticker">${row.Ticker}</td>`;
                } else if (col.color) {
                    const range = col.invert
                        ? (ranges[col.key] ? { min: ranges[col.key].max, max: ranges[col.key].min } : null)
                        : ranges[col.key];
                    html += colorCell(row[col.key], range, col.fmt);
                } else {
                    const v = row[col.key];
                    const txt = v != null && !isNaN(v) ? col.fmt(v) : '—';
                    html += `<td style="text-align:right;">${txt}</td>`;
                }
            });
            html += '</tr>';
        });

        html += '</tbody></table>';
        el.innerHTML = html;
    }

    // -------------------------------------------------------------------------
    // Load all panel data embedded in page and render
    // -------------------------------------------------------------------------
    const D = window._TOM_DATA;
    if (!D) return;

    // Panel 1 — Consistent TOM Longs
    const schemaLongs = [
        { key: 'Ticker',                    label: 'Ticker',         fmt: v => v,               color: false },
        { key: 'Full_LongTOM_Outperform',   label: 'Full Outperform',fmt: v => pct(v),          color: true  },
        { key: '5Y_LongTOM_Outperform',     label: '5Y Outperform',  fmt: v => pct(v),          color: true  },
        { key: '1Y_LongTOM_Outperform',     label: '1Y Outperform',  fmt: v => pct(v),          color: true  },
        { key: '1Y_TOM_WinRate',            label: '1Y Win Rate',    fmt: v => plainPct(v, 1),  color: true  },
    ];
    renderTable('tbl-longs', D.longs, schemaLongs, '1Y_LongTOM_Outperform');

    // Panel 2 — Vol/Hedge Timing (same schema)
    renderTable('tbl-vol', D.vol, schemaLongs, '1Y_LongTOM_Outperform');

    // Panel 3 — Newly Working Watch
    const schemaNewly = [
        { key: 'Ticker',                  label: 'Ticker',          fmt: v => v,      color: false },
        { key: 'Full_LongTOM_Outperform', label: 'Full Outperform', fmt: v => pct(v), color: true  },
        { key: '5Y_LongTOM_Outperform',   label: '5Y Outperform',   fmt: v => pct(v), color: true  },
        { key: '1Y_LongTOM_Outperform',   label: '1Y Outperform',   fmt: v => pct(v), color: true  },
        { key: 'Regime_1Y_vs_Full',       label: 'Regime Delta',    fmt: v => pct(v), color: true  },
    ];
    renderTable('tbl-newly', D.newly, schemaNewly, '1Y_LongTOM_Outperform');

    // Panel 4 — Short / Avoid TOM
    const schemaShort = [
        { key: 'Ticker',              label: 'Ticker',         fmt: v => v,              color: false },
        { key: '1Y_BH_CAGR',         label: 'B&H CAGR (1Y)',  fmt: v => pct(v),         color: true  },
        { key: '1Y_ShortTOM_CAGR',   label: 'Short TOM CAGR', fmt: v => pct(v),         color: true  },
        { key: '1Y_Avg_TOM_Return',   label: 'Avg TOM Return', fmt: v => pct(v, 4),      color: true,
          invert: true },
        { key: '1Y_TOM_WinRate',      label: 'TOM Win Rate',   fmt: v => plainPct(v, 1), color: true,
          invert: true },
    ];
    renderTable('tbl-short', D.short, schemaShort, '1Y_ShortTOM_CAGR');

})();
"""


# =============================================================================
# HTML BODY BUILDER
# =============================================================================

def rows_to_list(df, cols):
    """Convert DataFrame rows to list of dicts for JSON, NaN-safe."""
    if df.empty:
        return []
    subset = df[[c for c in cols if c in df.columns]].copy()
    # Replace inf/-inf with None, then NaN with None
    subset = subset.replace([float('inf'), float('-inf')], None)
    return json.loads(subset.to_json(orient='records'))


def build_body_html(dfs, writer):
    """Build full body HTML for DashboardWriter.write()."""

    summary    = parse_summary(dfs['summary'])
    longs_df, vol_df = filter_consistent(dfs['consistent'])
    newly_df   = filter_newly(dfs['newly'])
    short_df   = filter_short(dfs['short_1y'])

    run_date = summary.get('run_date', 'N/A')
    # Shorten date if it's datetime-like
    if ' ' in str(run_date):
        run_date = str(run_date).split(' ')[0]

    parts = []

    # ---- Stat bar ----
    parts.append(writer.stat_bar([
        ('Consistent TOM',   str(len(longs_df) + len(vol_df)), 'neutral'),
        ('Newly Working',    str(len(newly_df)),                'pos'),
        ('Stopped Working',  str(summary.get('stopped', '?')), 'neg'),
        ('Last Run',         run_date,                          'neutral'),
    ]))

    # ---- Page header ----
    parts.append(writer.build_header(
        'Turn-of-Month Signal Dashboard &nbsp;&mdash;&nbsp; '
        'Long TOM &bull; Vol Timing &bull; Newly Working &bull; Short/Avoid TOM'
    ))

    # ---- Explanation note ----
    parts.append(
        '<div class="tom-note" style="padding:0 0 4px 0;margin:0 0 18px 0;">'
        'TOM window = last 5 trading days of month through first 3 of next. '
        'Outperformance = Long-TOM CAGR minus Buy-and-Hold CAGR. '
        'Rerun <code>tom_full_scan_v3.py</code> monthly to refresh signals.'
        '</div>'
    )

    # ---- Panel 1: Consistent TOM Longs ----
    longs_html = (
        '<div class="tom-table-wrap"><div id="tbl-longs"></div></div>'
    )
    parts.append(writer.section(
        f'Consistent TOM Longs &nbsp;<span style="font-weight:400;font-size:0.85em;color:#888;">'
        f'{len(longs_df)} assets &mdash; positive Full + 5Y + 1Y, &ge;5Y history, B&H &gt; 0%</span>',
        longs_html,
        hint='Click column headers to sort'
    ))

    # ---- Panel 2: Vol/Hedge Timing ----
    vol_banner = (
        '<div class="tom-vol-banner">'
        '<strong>Volatility / Hedge Timing &mdash; not tradeable longs.</strong> '
        'These products decay permanently. Their TOM outperformance means they lose '
        '<em>less</em> during month-end windows. Use as a timing signal for hedge entry, '
        'not as a directional long trade.'
        '</div>'
    )
    vol_html = vol_banner + '<div class="tom-table-wrap"><div id="tbl-vol"></div></div>'
    parts.append(writer.section(
        f'Vol & Hedge Timing &nbsp;<span style="font-weight:400;font-size:0.85em;color:#888;">'
        f'{len(vol_df)} products</span>',
        vol_html,
        hint='Reduce hedge costs during TOM window'
    ))

    # ---- Panel 3: Newly Working Watch ----
    newly_banner = (
        '<div class="tom-warn-banner">'
        '<strong>Lower conviction &mdash; emerging signals only.</strong> '
        'These had negative TOM edge historically but are positive in the last 12 months. '
        'Could be regime shift or noise. Watch before trading; confirm with 5Y data turning positive.'
        '</div>'
    )
    newly_html = newly_banner + '<div class="tom-table-wrap"><div id="tbl-newly"></div></div>'
    parts.append(writer.section(
        f'Newly Working Watch &nbsp;<span style="font-weight:400;font-size:0.85em;color:#888;">'
        f'{len(newly_df)} assets &mdash; 1Y outperform &ge;10%, negative full history</span>',
        newly_html,
        hint='Emerging regime shift — monitor, do not trade blindly'
    ))

    # ---- Panel 4: Short / Avoid TOM ----
    short_banner = (
        '<div class="tom-short-banner">'
        '<strong>Good assets, bad at month-end.</strong> '
        'These have positive long-term B&H returns but reliably drop during TOM windows. '
        'Strategy: exit longs before TOM window and re-enter after, or short during TOM if conviction is high.'
        '</div>'
    )
    short_html = short_banner + '<div class="tom-table-wrap"><div id="tbl-short"></div></div>'
    parts.append(writer.section(
        f'Short / Avoid TOM &nbsp;<span style="font-weight:400;font-size:0.85em;color:#888;">'
        f'{len(short_df)} assets &mdash; positive B&H CAGR, negative 1Y TOM return</span>',
        short_html,
        hint='Exit before TOM window; re-enter after'
    ))

    parts.append(writer.footer())

    # ---- Embed data for JS ----
    long_cols  = ['Ticker', 'Full_LongTOM_Outperform', '5Y_LongTOM_Outperform',
                  '1Y_LongTOM_Outperform', '1Y_TOM_WinRate']
    newly_cols = ['Ticker', 'Full_LongTOM_Outperform', '5Y_LongTOM_Outperform',
                  '1Y_LongTOM_Outperform', 'Regime_1Y_vs_Full']
    short_cols = ['Ticker', '1Y_BH_CAGR', '1Y_ShortTOM_CAGR',
                  '1Y_Avg_TOM_Return', '1Y_TOM_WinRate']

    data_payload = {
        'longs': rows_to_list(longs_df,  long_cols),
        'vol':   rows_to_list(vol_df,    long_cols),
        'newly': rows_to_list(newly_df,  newly_cols),
        'short': rows_to_list(short_df,  short_cols),
    }

    data_js = (
        '<script>\nwindow._TOM_DATA = '
        + json.dumps(data_payload, ensure_ascii=False)
        + ';\n</script>\n'
    )

    return '\n'.join(parts), data_js


# =============================================================================
# MAIN
# =============================================================================

if __name__ == '__main__':
    print('\n' + '=' * 70)
    print('TOM DASHBOARD v1.0')
    print('=' * 70)

    # Load CSVs
    dfs = load_csvs()

    # Parse summary for reporting
    summary = parse_summary(dfs['summary'])
    print(f"\nSummary: {summary.get('consistent', '?')} consistent | "
          f"{summary.get('newly', '?')} newly working | "
          f"{summary.get('stopped', '?')} stopped | "
          f"Last run: {summary.get('run_date', 'N/A')}")

    # Build dashboard
    writer = DashboardWriter('tom-signals', 'Turn of Month Signals')
    body_html, data_js_block = build_body_html(dfs, writer)

    # Inject data block + render JS as extra_js
    combined_js = data_js_block + '\n<script>\n' + RENDER_JS + '\n</script>\n'

    writer.write(body_html, extra_css=EXTRA_CSS, extra_js=combined_js)

    print('\nDashboard written.')
    print('Run: python run_daily.py  (or check docs/tom-signals/index.html)')
    print('=' * 70 + '\n')

    # Verification
    print('Verification:')
    print('  [ok] v1.0 — initial build')
    print('  [ok] Windows Anaconda compatible (Python only, UTF-8)')
    print('  [ok] Full code provided')
    print('  [ok] Reads CSVs from same directory as script')
    print('  [ok] Filename: tom_dashboard_v1.0.py')
    print('  [ok] Run with: python tom_dashboard_v1.0.py')
