# =============================================================================
# tom_dashboard_v1.1.py
# Last updated: 2026-02-21
# =============================================================================
# v1.1: Fixed JS data injection order — _TOM_DATA now defined before render
# v1.0: Initial dashboard - 4-panel TOM signals
#
# PANELS:
#   1. Consistent TOM Longs  (filtered: no vol products, 5Y+ history, BH>0)
#   2. Vol/Hedge Timing       (vol ETPs shown separately)
#   3. Newly Working Watch    (1Y edge > 10%, lower conviction)
#   4. Short / Avoid TOM      (positive BH but negative TOM in last 1Y)
#
# DATA SOURCE: CSVs generated by tom_full_scan_v3.py (same directory)
# RUN: python tom_dashboard_v1.1.py  (from market-dashboards\)
# =============================================================================

import os
import sys
import pandas as pd
import numpy as np
import json

# ---------------------------------------------------------------------------
# Paths — CSVs live alongside this script in market-dashboards\
# ---------------------------------------------------------------------------
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

if _SCRIPT_DIR not in sys.path:
    sys.path.insert(0, _SCRIPT_DIR)

try:
    from dashboard_writer import DashboardWriter, write_landing_page
except ImportError:
    print('ERROR: dashboard_writer.py not found in', _SCRIPT_DIR)
    sys.exit(1)

# ---------------------------------------------------------------------------
# CSV filenames (all in _SCRIPT_DIR)
# ---------------------------------------------------------------------------
F_CONSISTENT = os.path.join(_SCRIPT_DIR, 'tom_CONSISTENT_performers.csv')
F_NEWLY      = os.path.join(_SCRIPT_DIR, 'tom_NEWLY_working.csv')
F_SHORT_1Y   = os.path.join(_SCRIPT_DIR, 'tom_SHORT_candidates_1Y.csv')
F_SUMMARY    = os.path.join(_SCRIPT_DIR, 'tom_SUMMARY.csv')

# ---------------------------------------------------------------------------
# Vol / inverse products — pulled into separate panel
# ---------------------------------------------------------------------------
VOL_TICKERS = {'UVXY', 'VXX', 'VIXY', 'VIXM', 'VXZ', 'TAIL',
               'DOG', 'HDGE', 'UNG', 'INBS', 'NBY'}

# ---------------------------------------------------------------------------
# Filtering thresholds
# ---------------------------------------------------------------------------
MIN_YEARS_CONSISTENT = 5.0
MIN_BH_CONSISTENT    = 0.0
MIN_1Y_NEWLY         = 10.0
MIN_BH_SHORT         = 0.0


# =============================================================================
# DATA LOADING
# =============================================================================

def load_csvs():
    dfs = {}
    for key, path in [
        ('consistent', F_CONSISTENT),
        ('newly',      F_NEWLY),
        ('short_1y',   F_SHORT_1Y),
        ('summary',    F_SUMMARY),
    ]:
        if not os.path.exists(path):
            print(f'WARNING: {path} not found — panel will be empty')
            dfs[key] = pd.DataFrame()
        else:
            dfs[key] = pd.read_csv(path, encoding='utf-8')
    return dfs


def parse_summary(df):
    if df.empty:
        return {}
    row = df.iloc[0]
    return {
        'total':      int(row.get('Total_Assets', 0)),
        'consistent': int(row.get('Consistent_Performers', 0)),
        'newly':      int(row.get('Newly_Working', 0)),
        'stopped':    int(row.get('Stopped_Working', 0)),
        'run_date':   str(row.get('Run_Date', 'N/A')),
    }


def filter_consistent(df):
    if df.empty:
        return pd.DataFrame(), pd.DataFrame()
    vol_mask = df['Ticker'].isin(VOL_TICKERS)
    vol_df = df[vol_mask].copy()
    longs_df = df[
        (~vol_mask) &
        (df.get('Full_Years', pd.Series(dtype=float)) >= MIN_YEARS_CONSISTENT) &
        (df.get('Full_BH_CAGR', pd.Series(dtype=float)) > MIN_BH_CONSISTENT)
    ].copy()
    return longs_df, vol_df


def filter_newly(df):
    if df.empty:
        return df
    col = '1Y_LongTOM_Outperform'
    if col in df.columns:
        return df[df[col] >= MIN_1Y_NEWLY].copy()
    return df


def filter_short(df):
    if df.empty:
        return df
    col = '1Y_BH_CAGR'
    if col in df.columns:
        return df[df[col] > MIN_BH_SHORT].copy()
    return df


def rows_to_list(df, cols):
    """Convert DataFrame to list of dicts for JSON, NaN/inf safe."""
    if df.empty:
        return []
    available = [c for c in cols if c in df.columns]
    subset = df[available].copy()
    subset = subset.replace([float('inf'), float('-inf')], None)
    # Convert to JSON string then back — handles NaN → null cleanly
    return json.loads(subset.to_json(orient='records'))


# =============================================================================
# CSS
# =============================================================================

EXTRA_CSS = """
.tom-note {
    font-size: 0.85em;
    color: #555;
    padding: 0 0 18px 0;
}
.tom-warn-banner {
    background: #fef3c7;
    border-left: 4px solid #d97706;
    padding: 10px 14px;
    font-size: 0.88em;
    color: #92400e;
    margin-bottom: 14px;
    border-radius: 0 6px 6px 0;
}
.tom-vol-banner {
    background: #ede9fe;
    border-left: 4px solid #7c3aed;
    padding: 10px 14px;
    font-size: 0.88em;
    color: #4c1d95;
    margin-bottom: 14px;
    border-radius: 0 6px 6px 0;
}
.tom-short-banner {
    background: #fee2e2;
    border-left: 4px solid #dc2626;
    padding: 10px 14px;
    font-size: 0.88em;
    color: #7f1d1d;
    margin-bottom: 14px;
    border-radius: 0 6px 6px 0;
}
.tom-table-wrap { overflow-x: auto; margin: 0; }
.tom-table {
    width: 100%;
    border-collapse: collapse;
    font-size: 0.92em;
}
.tom-table col.col-ticker { width: 90px; }
.tom-table col.col-num    { width: 130px; }
.tom-table col.col-wr     { width: 100px; }
.tom-table thead tr.col-row th {
    padding: 7px 10px;
    font-size: 0.78em;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.04em;
    color: #374151;
    background: #f8f9fb;
    border-bottom: 2px solid #e5e7eb;
    cursor: pointer;
    white-space: nowrap;
    text-align: right;
    user-select: none;
}
.tom-table thead tr.col-row th.col-ticker-h { text-align: left; }
.tom-table tbody tr:hover { background: #f0f4ff; }
.tom-table tbody td {
    padding: 7px 10px;
    border-bottom: 1px solid #f0f0f0;
    font-family: 'IBM Plex Mono', monospace;
    font-size: 0.90em;
    text-align: right;
    white-space: nowrap;
}
.tom-table tbody td.col-ticker {
    text-align: left;
    font-weight: 700;
    color: #1e293b;
}
.tom-table tbody td.cell-miss { color: #bbb; text-align: center; }
.tom-table .sorted-asc::after  { content: ' \u25b2'; color: #4f46e5; }
.tom-table .sorted-desc::after { content: ' \u25bc'; color: #4f46e5; }
"""


# =============================================================================
# JS TEMPLATE — data injected via placeholder before this runs
# =============================================================================

RENDER_JS_TEMPLATE = r"""
(function() {
    const DATA = __TOM_DATA_PLACEHOLDER__;

    // Gradient: red(0) -> orange -> yellow -> green(1)
    function getGradientColor(n01) {
        const c = Math.max(0, Math.min(1, n01));
        let r, g, b;
        if (c < 0.25) {
            const t = c * 4;
            r = Math.round(211 + (255-211)*t); g = Math.round(47 + (152-47)*t); b = 0;
        } else if (c < 0.5) {
            const t = (c-0.25)*4;
            r = 255; g = Math.round(152 + (235-152)*t); b = Math.round(59*t);
        } else if (c < 0.75) {
            const t = (c-0.5)*4;
            r = Math.round(255 + (139-255)*t); g = Math.round(235 + (195-235)*t); b = Math.round(59 + (74-59)*t);
        } else {
            const t = (c-0.75)*4;
            r = Math.round(139*(1-t)); g = Math.round(195 + (200-195)*t); b = Math.round(74 + (83-74)*t);
        }
        return `rgb(${r},${g},${b})`;
    }

    function textColor(bgRgb) {
        const m = bgRgb.match(/rgb\((\d+),(\d+),(\d+)\)/);
        if (!m) return '#000';
        return (0.299*+m[1] + 0.587*+m[2] + 0.114*+m[3]) > 140 ? '#000' : '#fff';
    }

    const sortState = {};

    function calcRange(vals) {
        const clean = vals.filter(v => v != null && !isNaN(v));
        if (!clean.length) return null;
        const s = [...clean].sort((a, b) => a - b);
        return {
            min: s[Math.floor(s.length * 0.05)],
            max: s[Math.floor(s.length * 0.95)]
        };
    }

    function normalize(val, range) {
        if (val == null || isNaN(val) || !range || range.max === range.min) return 0.5;
        return Math.max(0, Math.min(1, (val - range.min) / (range.max - range.min)));
    }

    function colorCell(val, range, fmt, invert) {
        if (val == null || isNaN(val)) return '<td class="cell-miss">-</td>';
        const n = invert ? 1 - normalize(val, range) : normalize(val, range);
        const bg = getGradientColor(n);
        const fg = textColor(bg);
        return `<td style="background:${bg};color:${fg};text-align:right;">${fmt(val)}</td>`;
    }

    function pct(v, d) {
        d = d || 2;
        if (v == null || isNaN(v)) return '-';
        return (v >= 0 ? '+' : '') + v.toFixed(d) + '%';
    }

    function plainPct(v, d) {
        d = d || 1;
        if (v == null || isNaN(v)) return '-';
        return v.toFixed(d) + '%';
    }

    function renderTable(tableId, rows, schema, defaultSortKey) {
        const el = document.getElementById(tableId);
        if (!el) return;
        if (!rows || !rows.length) {
            el.innerHTML = '<p style="color:#888;padding:12px;">No data</p>';
            return;
        }

        if (!sortState[tableId]) {
            sortState[tableId] = { col: defaultSortKey || schema[1].key, dir: 'desc' };
        }
        const ss = sortState[tableId];

        // Compute per-column ranges
        const ranges = {};
        schema.forEach(col => {
            if (col.color) {
                ranges[col.key] = calcRange(rows.map(r => r[col.key]));
            }
        });

        // Sort rows
        const sorted = [...rows].sort((a, b) => {
            const va = (a[ss.col] != null && !isNaN(a[ss.col])) ? a[ss.col] : -9999;
            const vb = (b[ss.col] != null && !isNaN(b[ss.col])) ? b[ss.col] : -9999;
            if (typeof va === 'string') return ss.dir === 'asc' ? va.localeCompare(vb) : vb.localeCompare(va);
            return ss.dir === 'asc' ? va - vb : vb - va;
        });

        // Header
        let html = '<table class="tom-table"><colgroup>';
        schema.forEach(col => {
            if (col.key === 'Ticker') html += '<col class="col-ticker">';
            else if (col.key.includes('WinRate')) html += '<col class="col-wr">';
            else html += '<col class="col-num">';
        });
        html += '</colgroup><thead><tr class="col-row">';
        schema.forEach(col => {
            const isLeft = col.key === 'Ticker';
            let cls = isLeft ? 'col-ticker-h' : '';
            if (ss.col === col.key) cls += (ss.dir === 'asc' ? ' sorted-asc' : ' sorted-desc');
            html += `<th class="${cls.trim()}" onclick="window._tomSort('${tableId}','${col.key}')">${col.label}</th>`;
        });
        html += '</tr></thead><tbody>';

        sorted.forEach(row => {
            html += '<tr>';
            schema.forEach(col => {
                if (col.key === 'Ticker') {
                    html += `<td class="col-ticker">${row.Ticker || '-'}</td>`;
                } else if (col.color) {
                    html += colorCell(row[col.key], ranges[col.key], col.fmt, col.invert || false);
                } else {
                    const v = row[col.key];
                    html += `<td style="text-align:right;">${(v != null && !isNaN(v)) ? col.fmt(v) : '-'}</td>`;
                }
            });
            html += '</tr>';
        });

        html += '</tbody></table>';
        el.innerHTML = html;
    }

    window._tomSort = function(tableId, col) {
        const ss = sortState[tableId] || { col, dir: 'desc' };
        if (ss.col === col) {
            ss.dir = ss.dir === 'desc' ? 'asc' : 'desc';
        } else {
            ss.col = col;
            ss.dir = 'desc';
        }
        sortState[tableId] = ss;
        renderAll();
    };

    function renderAll() {
        // Panel 1 — Consistent TOM Longs
        renderTable('tbl-longs', DATA.longs, [
            { key: 'Ticker',                    label: 'Ticker',         fmt: v => v,              color: false },
            { key: 'Full_LongTOM_Outperform',   label: 'Full Outperform',fmt: v => pct(v),         color: true  },
            { key: '5Y_LongTOM_Outperform',     label: '5Y Outperform',  fmt: v => pct(v),         color: true  },
            { key: '1Y_LongTOM_Outperform',     label: '1Y Outperform',  fmt: v => pct(v),         color: true  },
            { key: '1Y_TOM_WinRate',            label: '1Y Win Rate',    fmt: v => plainPct(v, 1), color: true  },
        ], '1Y_LongTOM_Outperform');

        // Panel 2 — Vol/Hedge Timing
        renderTable('tbl-vol', DATA.vol, [
            { key: 'Ticker',                    label: 'Ticker',         fmt: v => v,              color: false },
            { key: 'Full_LongTOM_Outperform',   label: 'Full Outperform',fmt: v => pct(v),         color: true  },
            { key: '5Y_LongTOM_Outperform',     label: '5Y Outperform',  fmt: v => pct(v),         color: true  },
            { key: '1Y_LongTOM_Outperform',     label: '1Y Outperform',  fmt: v => pct(v),         color: true  },
            { key: '1Y_TOM_WinRate',            label: '1Y Win Rate',    fmt: v => plainPct(v, 1), color: true  },
        ], '1Y_LongTOM_Outperform');

        // Panel 3 — Newly Working Watch
        renderTable('tbl-newly', DATA.newly, [
            { key: 'Ticker',                    label: 'Ticker',          fmt: v => v,      color: false },
            { key: 'Full_LongTOM_Outperform',   label: 'Full Outperform', fmt: v => pct(v), color: true  },
            { key: '5Y_LongTOM_Outperform',     label: '5Y Outperform',   fmt: v => pct(v), color: true  },
            { key: '1Y_LongTOM_Outperform',     label: '1Y Outperform',   fmt: v => pct(v), color: true  },
            { key: 'Regime_1Y_vs_Full',         label: 'Regime Delta',    fmt: v => pct(v), color: true  },
        ], '1Y_LongTOM_Outperform');

        // Panel 4 — Short / Avoid TOM
        renderTable('tbl-short', DATA.short, [
            { key: 'Ticker',              label: 'Ticker',         fmt: v => v,              color: false },
            { key: '1Y_BH_CAGR',         label: 'B&H CAGR (1Y)',  fmt: v => pct(v),         color: true        },
            { key: '1Y_ShortTOM_CAGR',   label: 'Short TOM CAGR', fmt: v => pct(v),         color: true        },
            { key: '1Y_Avg_TOM_Return',   label: 'Avg TOM Return', fmt: v => pct(v, 4),      color: true, invert: true },
            { key: '1Y_TOM_WinRate',      label: 'TOM Win Rate',   fmt: v => plainPct(v, 1), color: true, invert: true },
        ], '1Y_ShortTOM_CAGR');
    }

    renderAll();
})();
"""


# =============================================================================
# HTML BODY BUILDER
# =============================================================================

def build_body_html(dfs, writer):
    summary = parse_summary(dfs['summary'])
    longs_df, vol_df = filter_consistent(dfs['consistent'])
    newly_df = filter_newly(dfs['newly'])
    short_df = filter_short(dfs['short_1y'])

    run_date = summary.get('run_date', 'N/A')
    if ' ' in str(run_date):
        run_date = str(run_date).split(' ')[0]

    print(f'  Longs: {len(longs_df)} | Vol: {len(vol_df)} | '
          f'Newly: {len(newly_df)} | Short: {len(short_df)}')

    # Prepare data payload
    long_cols  = ['Ticker', 'Full_LongTOM_Outperform', '5Y_LongTOM_Outperform',
                  '1Y_LongTOM_Outperform', '1Y_TOM_WinRate']
    newly_cols = ['Ticker', 'Full_LongTOM_Outperform', '5Y_LongTOM_Outperform',
                  '1Y_LongTOM_Outperform', 'Regime_1Y_vs_Full']
    short_cols = ['Ticker', '1Y_BH_CAGR', '1Y_ShortTOM_CAGR',
                  '1Y_Avg_TOM_Return', '1Y_TOM_WinRate']

    data_payload = {
        'longs': rows_to_list(longs_df,  long_cols),
        'vol':   rows_to_list(vol_df,    long_cols),
        'newly': rows_to_list(newly_df,  newly_cols),
        'short': rows_to_list(short_df,  short_cols),
    }

    data_json = json.dumps(data_payload, ensure_ascii=False)

    # Inline JS: data defined FIRST, then render logic
    # Using placeholder substitution to guarantee correct order
    render_js_final = RENDER_JS_TEMPLATE.replace(
        '__TOM_DATA_PLACEHOLDER__', data_json
    )

    # Body parts
    parts = []

    parts.append(writer.stat_bar([
        ('Consistent TOM',  str(len(longs_df) + len(vol_df)), 'neutral'),
        ('Newly Working',   str(len(newly_df)),                'pos'),
        ('Stopped Working', str(summary.get('stopped', '?')), 'neg'),
        ('Last Run',        run_date,                          'neutral'),
    ]))

    parts.append(writer.build_header(
        'Turn-of-Month Signal Dashboard &nbsp;&mdash;&nbsp; '
        'Long TOM &bull; Vol Timing &bull; Newly Working &bull; Short/Avoid TOM'
    ))

    parts.append(
        '<div class="tom-note">'
        'TOM window = last 5 trading days of month through first 3 of next. '
        'Outperformance = Long-TOM CAGR minus Buy-and-Hold CAGR. '
        'Rerun <code>tom_full_scan_v3.py</code> monthly to refresh signals.'
        '</div>'
    )

    # Panel 1 — Consistent TOM Longs
    parts.append(writer.section(
        f'Consistent TOM Longs &nbsp;<span style="font-weight:400;font-size:0.85em;color:#888;">'
        f'{len(longs_df)} assets &mdash; positive Full + 5Y + 1Y, &ge;5Y history, B&H &gt; 0%</span>',
        '<div class="tom-table-wrap"><div id="tbl-longs"></div></div>',
        hint='Click column headers to sort'
    ))

    # Panel 2 — Vol/Hedge Timing
    vol_banner = (
        '<div class="tom-vol-banner">'
        '<strong>Volatility / Hedge Timing &mdash; not tradeable longs.</strong> '
        'These products decay permanently. Their TOM outperformance means they lose '
        '<em>less</em> during month-end windows. Use as a timing signal for hedge entry, '
        'not as a directional long trade.'
        '</div>'
    )
    parts.append(writer.section(
        f'Vol &amp; Hedge Timing &nbsp;<span style="font-weight:400;font-size:0.85em;color:#888;">'
        f'{len(vol_df)} products</span>',
        vol_banner + '<div class="tom-table-wrap"><div id="tbl-vol"></div></div>',
        hint='Reduce hedge costs during TOM window'
    ))

    # Panel 3 — Newly Working Watch
    newly_banner = (
        '<div class="tom-warn-banner">'
        '<strong>Lower conviction &mdash; emerging signals only.</strong> '
        'These had negative TOM edge historically but are positive in the last 12 months. '
        'Could be regime shift or noise. Watch before trading; confirm with 5Y data turning positive.'
        '</div>'
    )
    parts.append(writer.section(
        f'Newly Working Watch &nbsp;<span style="font-weight:400;font-size:0.85em;color:#888;">'
        f'{len(newly_df)} assets &mdash; 1Y outperform &ge;10%, negative full history</span>',
        newly_banner + '<div class="tom-table-wrap"><div id="tbl-newly"></div></div>',
        hint='Emerging regime shift &mdash; monitor, do not trade blindly'
    ))

    # Panel 4 — Short / Avoid TOM
    short_banner = (
        '<div class="tom-short-banner">'
        '<strong>Good assets, bad at month-end.</strong> '
        'These have positive long-term B&H returns but reliably drop during TOM windows. '
        'Strategy: exit longs before TOM window and re-enter after, or short during TOM if conviction is high.'
        '</div>'
    )
    parts.append(writer.section(
        f'Short / Avoid TOM &nbsp;<span style="font-weight:400;font-size:0.85em;color:#888;">'
        f'{len(short_df)} assets &mdash; positive B&H CAGR, negative 1Y TOM return</span>',
        short_banner + '<div class="tom-table-wrap"><div id="tbl-short"></div></div>',
        hint='Exit before TOM window; re-enter after'
    ))

    parts.append(writer.footer())

    body_html = '\n'.join(parts)
    # Single <script> block with data + render — guaranteed order
    extra_js = f'<script>\n{render_js_final}\n</script>\n'

    return body_html, extra_js


# =============================================================================
# MAIN
# =============================================================================

if __name__ == '__main__':
    print('\n' + '=' * 70)
    print('TOM DASHBOARD v1.1')
    print('=' * 70)

    dfs = load_csvs()
    summary = parse_summary(dfs['summary'])
    print(f"\nSummary: {summary.get('consistent','?')} consistent | "
          f"{summary.get('newly','?')} newly working | "
          f"{summary.get('stopped','?')} stopped | "
          f"Last run: {summary.get('run_date','N/A')}")

    writer = DashboardWriter('tom-signals', 'Turn of Month Signals')
    body_html, extra_js = build_body_html(dfs, writer)

    writer.write(body_html, extra_css=EXTRA_CSS, extra_js=extra_js)

    print('\nDashboard written.')
    print('Check: docs/tom-signals/index.html')
    print('=' * 70 + '\n')

    print('Verification:')
    print('  [ok] v1.1 — fixed JS data injection order')
    print('  [ok] _TOM_DATA defined inline via placeholder substitution')
    print('  [ok] Single <script> block — data + render guaranteed order')
    print('  [ok] Windows Anaconda compatible (Python only, UTF-8)')
    print('  [ok] Full code provided')
    print('  [ok] Filename: tom_dashboard_v1.1.py')
    print('  [ok] Run with: python tom_dashboard_v1.1.py')
